// Copyright (C) 2012-2016 The VPaint Developers.
// See the COPYRIGHT file at the top-level directory of this distribution
// and at https://github.com/dalboris/vpaint/blob/master/COPYRIGHT
//
// This file is part of VPaint, a vector graphics editor. It is subject to the
// license terms and conditions in the LICENSE.MIT file found in the top-level
// directory of this distribution and at http://opensource.org/licenses/MIT

#ifndef VECCURVEINPUTSAMPLE_H
#define VECCURVEINPUTSAMPLE_H

#include <glm/vec2.hpp>
#include <vector>

/// \class VecCurveInputSample
/// \brief A struct that represents a raw input sample (e.g., from a mouse
/// or a pen tablet).
///
/// These VecCurveInputSample are the input to the curve fitting algorithm, which
/// produces EdgeGeometrySample as output.
///
struct VecCurveInputSample
{
    /// Position of the mouse sample in scene coordinates.
    ///
    glm::vec2 position;

    /// Desired width of the curve at this mouse sample, in scene coordinates.
    /// It is typically derived from pen tablet pressure or sketch tool
    /// settings.
    ///
    float width;

    /// Time elapsed, in seconds, between first mouse sample and this mouse sample
    /// of a given stroke.
    ///
    float time;

    /// Resolution of the input in scene coordinates. For instance, at a 200%
    /// zoom level, and using mouse input generated by Qt as integer, then the
    /// resolution is 1px in view coordinates, therefore 0.5 in scene
    /// coordinates.
    ///
    /// This is used to discard consecutive input samples which are too close
    /// to each others, and to know how far the fitted curve may deviate from
    /// the input when no smoothing is applied. Indeed, even without smoothing,
    /// input point are not exactly extrapolated. The rationale is that in
    /// fact, the mouse did not actually pass exactly through the given input,
    /// due to the limited resolution. Therefore, it does not make so much
    /// sense to exactly extrapolate the input, and in fact, doing so generates
    /// unwanted artifacts.
    ///
    float resolution;

    /// Constructs a mouse sample.
    ///
    VecCurveInputSample() :

        position(glm::vec2(0.0f, 0.0f)),
        width(0.0f),
        time(0.0f),
        resolution(0.0f)

    {}

    /// Constructs a mouse sample.
    ///
    VecCurveInputSample(
            const glm::vec2 & position,
            float width,
            float time,
            float resolution) :

        position(position),
        width(width),
        time(time),
        resolution(resolution)

    {}
};

#endif // VECCURVEINPUTSAMPLE_H
